### ISSUE TITLE
Please upgrade to latest version of Couchbase Java SDK

### ISSUE THREAD

**Issue by programmatix** [DataGrip/couchbase-jdbc-driver#2]
The currently used version is 3.0.8, which is rather ancient.  

The latest provides some improvements including bundling the root cluster certificate for our cloud product, Capella, making it much easier for users to get up and running in that environment.

**Comment by mgroves** [comment]
I attempted a naïve upgrade by just changing the dependency version, and got other compiler errors. 

See more here: https://issues.couchbase.com/browse/JCBC-2003

**Comment by dnault** [comment]
PR to help with the upgrade: https://github.com/DataGrip/couchbase-jdbc-driver/pull/3

**Comment by kornilova203** [comment]
Thanks a lot
I've merged #3
We'll make new version available in DataGrip soon
